# Generated by Django 5.1 on 2024-08-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_first_name_userprofile_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='second_name',
        ),
    ]
