# Generated by Django 5.1 on 2024-08-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_category_name_alter_product_name'),
        ('user', '0007_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('products', models.ManyToManyField(related_name='orders', to='product.product')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='user.userprofile')),
            ],
        ),
    ]
